export const mysqlDateFormat = 'YYYY-MM-DD HH:mm:SS';
export const genres = [
    'JRPG',
    'Action',
    'Action RPG',
    'Adventure',
    'RPG',
    'Open World',
    'Shooter',
    'VR',
    'MMO',
    'Simulation',
    'Rhythm',
    'Strategy RPG',
    'Base Builder',
    'Stealth',
    'Roguelike',
    'Puzzle',
    'Survival',
    'Horror',
    'TCG',
    'Crafting',
    'Sidescroller',
    'Platformer',
    'Strategy'
].sort();
export const systems = [
    'PlayStation',
    'PlayStation 2',
    'PlayStation 3',
    'PlayStation 4',
    'Xbox',
    'Xbox 360',
    'Xbox One',
    'PC',
    'Nintendo Switch',
    'Nintendo 3DS',
    'Nintendo DS',
    'PSP',
    'PS Vita',
    'Game Boy Advance',
    'Nintendo 64',
    'Nintendo GameCube',
    'Wii',
    'Wii U',
    'Sega Dreamcast',
    'Sega Genesis',
    'Sega Saturn',
    'NES',
    'SNES'
].sort();
