export type ADD_GAME = 'ADD_GAME';
export type DELETE_GAME = 'DELETE_GAME;';
export type UPDATE_GAMES = 'UPDATE_GAMES';
export type UPDATE_GAME = 'UPDATE_GAME';
export type UPDATE_USER = 'UPDATE_USER';

export const ADD_GAME: ADD_GAME = 'ADD_GAME';
export const DELETE_GAME: DELETE_GAME = 'DELETE_GAME;';
export const UPDATE_GAMES: UPDATE_GAMES = 'UPDATE_GAMES';
export const UPDATE_GAME: UPDATE_GAME = 'UPDATE_GAME';
export const UPDATE_USER: UPDATE_USER = 'UPDATE_USER';
